package org.tempuri.action;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-06-26T13:37:16.996-05:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/action/", name = "wsBTHabilitarTINSoapPort")
@XmlSeeAlso({bantotal.dlya.com.uy.btservice.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsBTHabilitarTINSoapPort {

    @WebMethod(operationName = "Execute", action = "http://tempuri.org/action/action/AWSBTHABILITARTIN.Execute")
    @WebResult(name = "wsBTHabilitarTIN.ExecuteResponse", targetNamespace = "http://tempuri.org/action/", partName = "parameters")
    public WsBTHabilitarTINExecuteResponse execute(
        @WebParam(partName = "parameters", name = "wsBTHabilitarTIN.Execute", targetNamespace = "http://tempuri.org/action/")
        WsBTHabilitarTINExecute parameters
    );
}
